version: "0.1"
services:
    calc_server:
        build: .
        container_name: distributedCalculator
        ports:
            - 50051:50051
        volumes:
            - ./server/:/go/src/github.com/Wdrwoman/distributedCalculator/server/
            - ./proto/:/go/src/github.com/Wdrwoman/distributedCalculator/proto/

